kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}

      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}

      probeSelector: {}
      probeNamespaceSelector: {}