argo-cd:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  server:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  repoServer:
    volumes:
      - name: custom-tools
        emptyDir: {}

    initContainers:
      - name: download-helm
        image: alpine:3.20
        command: [sh, -c]
        args:
          - |
            wget -qO- https://get.helm.sh/helm-v3.20.2-linux-amd64.tar.gz \
            | tar -xz
            cp linux-amd64/helm /custom-tools/helm
            chmod +x /custom-tools/helm
        volumeMounts:
          - name: custom-tools
            mountPath: /custom-tools

    volumeMounts:
      - name: custom-tools
        mountPath: /usr/local/bin/helm
        subPath: helm
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  notifications:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

