# Enable metrics for the Application Controller (Port 8082)
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

# Enable metrics for the Argo CD API Server (Port 8083)
server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

# Enable metrics for the Repo Server (Port 8084)
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

# Enable metrics for the ApplicationSet Controller (Port 8080/8082)
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

# Enable metrics for Dex (If using internal authentication)
dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
